### ISSUE TITLE
Follow ns-3 coding guidelines

### ISSUE THREAD

**Issue by mohittahiliani** [shrinidhi99/set-associative-hash-fq-codel-ns-3#6]
I noticed that the source code does not currently follow the coding guidelines (i.e., formatting of code and naming the variables, indentation, etc).

See this link for guidance:
https://www.nsnam.org/develop/contributing-code/coding-style/

Note: if you're planning to use check-style.py in utils/ directory to make the necessary corrections, ensure that running check-style.py does not make any change to the existing codebase.

Let me know if you need help in this.

**Comment by shrinidhi99** [comment]
Sir @AB261 has taken care of it. May I close this issue?

**Comment by mohittahiliani** [comment]
I see many changes still pending. Let's keep this open
