### ISSUE TITLE
Remove NS_LOG_DEBUG statements and other similar code

### ISSUE THREAD

**Issue by mohittahiliani** [shrinidhi99/set-associative-hash-fq-codel-ns-3#7]
All NS_LOG_DEBUG statements can be removed now. 

Also remove the code which might be commented and is unnecessary + the code which has been kept only for debugging purposes.

**Comment by shrinidhi99** [comment]
Ok sir.

**Comment by shrinidhi99** [comment]
Sir is the issue resolved?
